### ISSUE TITLE
Cannot find module './../../rtp_media_config' on ./initLicode.sh

### ISSUE THREAD

**Issue by Javiiiie** [lynckia/licode#1395]
Hello I'm trying to install licode but I'm getting stuck with this error for 2 days already.
I tried to reinstall absolutly everything, had some problems with boost but I think it's already fixed.

I get a similar error before "Cannot find module 'uuid/v4'", I fixed it easily with:
`npm install uuid`

I can't find any info about this error, could someone help me please?

```
Error: Cannot find module './../../rtp_media_config'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/veloria/licode/erizo_controller/erizoJS/erizoJS.js:10:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)


```

I'm working in ubuntu 14.04

**Comment by lidedongsn** [comment]
./scripts/installUbuntuDeps.sh
./scripts/installErizo.sh -f
./scripts/installNuve.sh
./scripts/installBasicExample.sh
then
./scripts/initLicode.sh
./scripts/initBasicExample.sh 

in ./scripts/installErizo.sh
```
cp $PATHNAME/rtp_media_config_default.js $ROOT/rtp_media_config.js
```
rtp_media_config_default.js in **scripts** folder

**Comment by Sleepingbug** [comment]
download the latest code...rtp_media_config.js has been added
